ARM: s3c2440: gta02: Select missing S3C_DEV_USB_HOST
The gta02 mach file references the ohci device.
So we need to select S3C_DEV_USB_HOST to have the device available.

This fixes the following linker error:
	arch/arm/mach-s3c2440/built-in.o: In function `gta02_machine_init':
	mach-gta02.c:(.init.text+0x370): undefined reference to `s3c_ohci_set_platdata'
	arch/arm/mach-s3c2440/built-in.o:(.init.data+0xac): undefined reference to `s3c_device_ohci'

Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>